services:
  app:
    build:
      target: production
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes: [] # Remove development volumes
    develop:
      watch: [] # Disable watch mode in production

  # Remove development-only services
  phpmyadmin:
    profiles: ["debug"]

  mailhog:
    profiles: ["debug"]

  # Add nginx load balancer for production
  nginx:
    image: nginx:alpine
    container_name: adalanka_nginx_lb
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - app
    profiles: ["production"]
